<?php $_cartQty = $this->getSummaryCount() ?>
<div id ="mini_cart_block">
    <div class="block-cart mini_cart_ajax">
            <div class="block-cart">
                <?php $_cartQty = $this->getSummaryCount() ?>
                <div class="cart-mini-title">
                    <a class="shopping-cart" href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>">
            
                    <span class="cart-count">
<?php 
//override all cart-count with custom count that is items X qty X count_per_pack
$items = Mage::getSingleton('checkout/session')->getQuote()->getAllItems();

$fullqty = 0;
foreach($items as $item) {
	$count_per_pack = $item->getProduct()->getData('count_per_pack');
	if ($count_per_pack && $count_per_pack != 0) {
		$fullqty += ($count_per_pack * $item->getQty()) ;
	} else {
		$fullqty += $item->getQty();
	}
}
	//rebuild fullqty number to reduce the display size
	if (substr($fullqty, -3) === "000") {
		$fullqty = substr_replace($fullqty, 'K', -3);
	} else if (strlen($fullqty) === 4 && substr($fullqty, -2) === "00") {
		$rebuild = substr($fullqty, 0, 1) . "." . substr($fullqty, 1, 1) . "K";
		$fullqty = $rebuild;
	} else if (strlen($fullqty) == 5 && substr($fullqty, -2) === "00") {
		$rebuild = substr($fullqty, 0, 2) . "." . substr($fullqty, 2, 1) . "K";
		$fullqty = $rebuild;
	}

echo $fullqty;
 ?>									
					<?php /* echo "hi"; ?><?php if($_cartQty<1) { echo $this->__('0'); } else { echo $_cartQty; } ?><?php echo $this->__(' '); ?><?php if($_cartQty>1) { echo $this->__(''); } else { echo $this->__(''); }  */?>
                   
                   <span class="arrows"></span>
                    </a>
                </div>
                <div class="top-cart-content">
                    <?php $_items = $this->getRecentItems() ?>
                    <?php if (count($_items)): ?>
                        <ol id="cart-sidebar" class="mini-products-list">
                            <?php foreach ($_items as $_item): ?>
                                <?php echo $this->getItemHtml($_item) ?>
                            <?php endforeach; ?>
                        </ol>
                        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
                    <?php else: ?>
                        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                    <?php endif ?>
                    <div class="top-subtotal"><?php echo $this->__('Subtotal') ?>: <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></div>
                    <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <div class="actions">
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                        </div>
                    <?php endif ?>
                </div>
            </div>

    </div>
</div>
<script type="text/javascript">
    var ajaxCartCfg = {
        'removeConfirm' : '<?php echo $this-> __('Are you sure you would like to remove this item ?') ?>',
    };
</script>
