
<?php
?>
<?php
$helper = Mage::helper('fbfanbox');
$fbfanbox = $helper->getGeneralCfg();
if(isset($fbfanbox['enabled']) && $fbfanbox['enabled'])
{	
	echo '<div id="fb-root"></div>';
    $box_content="";
    $box_content .='<div class="fb-page" data-href="'.$fbfanbox['fb_page_url'].'" data-width="'.$fbfanbox['width'].'" data-height="'.$fbfanbox['height'].'" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="true">
    <div class="fb-xfbml-parse-ignore"><blockquote cite="'.$fbfanbox['fb_page_url'].'"><a href="'.$fbfanbox['fb_page_url'].'">"'.$fbfanbox['fb_page_url'].'"</a></blockquote></div></div>';
    
    echo("<div id='fbfanbox'>");
    echo($box_content);
    echo("</div>");

}
?>
