<?php
    $_category  = Mage::registry('current_category');
    if($_category){
        $_helper    = $this->helper('catalog/output');
        $_imgHtml   = '';
        if ($_imgUrl = $_category->getImageUrl()) {
            $_imgHtml = '<div class="categories-img"><p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p></div>';
            echo $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        }
    }
?>
    
